# -*- coding: utf-8 -*-
"""ASSIGNMENT4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfLa0PV5WhU8rgGe4P_DGIpqYCpfhU3c
"""

# Step 1: Mount your google drive
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Set plot styles
sns.set(style='whitegrid')
# %matplotlib inline

# Load the dataset
df = pd.read_csv("/content/drive/MyDrive/data_ndv/Titanic-Dataset.csv")  # Replace with correct path if needed
df.head()

#DATA OVERVIEW
# Basic info
df.info()

# Summary statistics
df.describe(include='all')

# Check for duplicates
print(f"Duplicates: {df.duplicated().sum()}")

#DATA CLEANING
# Check missing values
df.isnull().sum()

# Handle missing values
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Cabin'].fillna('Unknown', inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# Drop irrelevant columns
df.drop(columns=['PassengerId', 'Name', 'Ticket'], inplace=True)

# Convert 'Sex' and 'Embarked' to category types
df['Sex'] = df['Sex'].astype('category')
df['Embarked'] = df['Embarked'].astype('category')

# Univariate Analysis
# Count plots
sns.countplot(x='Survived', data=df)
plt.title('Survival Count')
plt.show()

sns.countplot(x='Pclass', data=df)
plt.title('Passenger Class Count')
plt.show()

# Distribution of Age
sns.histplot(df['Age'], bins=30, kde=True)
plt.title('Age Distribution')
plt.show()

# Boxplot for Fare
sns.boxplot(x='Fare', data=df)
plt.title('Fare Distribution')
plt.show()

#Bivariate Analysis
# Pairplot
sns.pairplot(df[['Survived', 'Age', 'Fare', 'Pclass']], hue='Survived')
plt.show()

# Heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# Groupby survival by Sex and Pclass
print(df.groupby(['Sex', 'Pclass'])['Survived'].mean())

#Bonus: Violin Plot + Feature Engineering
# Violin Plot of Age by Survived
sns.violinplot(x='Survived', y='Age', data=df)
plt.title('Age Distribution by Survival')
plt.show()

# Feature Engineering: FamilySize
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

sns.boxplot(x='Survived', y='FamilySize', data=df)
plt.title('Survival by Family Size')
plt.show()

#1. Sex is a strong predictor: Females had a significantly higher survival rate.
#2. Pclass matters: First class passengers had higher survival rates.
#3. Younger passengers were more likely to survive.
#4. Larger families (FamilySize > 4) had lower survival rates.
#5. Fare is positively correlated with survival – those who paid more had better chances.
