# -*- coding: utf-8 -*-
"""ASSIGNMENT5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJ9bYhKIKR4WPQROft7CFfjK5fy-OA9r
"""

# Step 1: Mount your google drive
from google.colab import drive
drive.mount('/content/drive')

# Step 1: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_1samp, chi2_contingency

# Step 2: Load the Dataset
df = pd.read_csv('/content/drive/MyDrive/data_ndv/sales_data_sample.csv', encoding='ISO-8859-1')
df.head()

df.tail()

#Step 3: Check Columns and Data Types
print(df.columns)
df.info()

# Step 4: Clean & Prepare Data
# Drop rows with missing numerical values
df = df.dropna(subset=['QUANTITYORDERED', 'PRICEEACH', 'SALES', 'MSRP'])

# Create derived column: PROFIT (revenue - cost price approximation)
df['COST'] = df['QUANTITYORDERED'] * df['PRICEEACH']
df['PROFIT'] = df['SALES'] - df['COST']

#Step 5: Summary Statistics
summary_stats = df[['QUANTITYORDERED', 'PRICEEACH', 'SALES', 'MSRP', 'COST', 'PROFIT']].agg(['mean', 'median', 'std', 'min', 'max', 'sum'])
summary_stats

# Step 6: Visualizations
# Boxplot of PROFIT
plt.figure(figsize=(8, 5))
sns.boxplot(x=df['PROFIT'])
plt.title("Boxplot of Profit")
plt.show()

# Histogram of SALES
plt.figure(figsize=(8, 5))
plt.hist(df['SALES'], bins=30, color='skyblue')
plt.title("Histogram of Sales")
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.show()

# Step 7: Hypothesis Test 1 – One Sample t-test
# H₀: The mean sales is $3,000
# H₁: The mean sales is different from $3,000
t_stat, p_val = ttest_1samp(df['SALES'], 3000)
print(f"t-statistic = {t_stat:.4f}, p-value = {p_val:.4f}")
if p_val < 0.05:
    print("Reject H₀: Mean sales is significantly different from 3000.")
else:
    print("Fail to reject H₀: No significant difference in mean sales.")
# Visualize the distribution of SALES with mean line and hypothesized mean (3000)
plt.figure(figsize=(10, 6))
sns.histplot(df['SALES'], kde=True, bins=30, color='lightblue')
plt.axvline(df['SALES'].mean(), color='green', linestyle='--', label=f"Sample Mean = {df['SALES'].mean():.2f}")
plt.axvline(3000, color='red', linestyle='-', label="Hypothesized Mean = 3000")
plt.title("One-Sample t-test: Distribution of Sales")
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.legend()
plt.show()

# Step 8: Hypothesis Test 2 – Chi-Square Test
# H₀: ProductLine and DealSize are independent
# H₁: There is an association between ProductLine and DealSize
contingency_table = pd.crosstab(df['PRODUCTLINE'], df['DEALSIZE'])
chi2, p, dof, expected = chi2_contingency(contingency_table)
print(f"Chi-square = {chi2:.4f}, p-value = {p:.4f}")
if p < 0.05:
    print("Reject H₀: There is a relationship between PRODUCTLINE and DEALSIZE.")
else:
    print("Fail to reject H₀: PRODUCTLINE and DEALSIZE are independent.")
# Visualize the contingency table as a heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(contingency_table, annot=True, fmt='d', cmap='YlGnBu')
plt.title("Chi-Square Test: PRODUCTLINE vs DEALSIZE")
plt.xlabel("Deal Size")
plt.ylabel("Product Line")
plt.show()

# Step 9: Bonus – Correlation Heatmap
plt.figure(figsize=(8,6))
sns.heatmap(df[['QUANTITYORDERED', 'PRICEEACH', 'SALES', 'MSRP', 'PROFIT']].corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# Step 10: Bonus – Pivot Table Summary
pivot = pd.pivot_table(df, values='SALES', index='PRODUCTLINE', columns='DEALSIZE', aggfunc='mean')
pivot

# Step 11: Markdown Summary
### 📊 Key Findings

# - Mean Sales was found to be significantly different from $3,000 based on a one-sample t-test (p < 0.05).
# - Chi-square test revealed a significant relationship between `PRODUCTLINE` and `DEALSIZE`.
# - Profit varied widely across records, with some products showing negative profit (potential losses).
# - Correlation heatmap shows strong positive relationship between `QUANTITYORDERED`, `SALES`, and `PROFIT`.
# - Pivot table analysis reveals which product lines perform best under different deal sizes.
